/**
 * CL 26/27 — ligafasens 144 kampe fra lodtrækningen i Monaco 27. august 2026.
 *
 * Hvert hold møder 8 forskellige modstandere (2 fra hvert seedingslag), 4 kampe
 * hjemme og 4 ude — hjemme/ude ligger fast fra lodtrækningen. Navnene er
 * katalogets kanoniske navne (cl2627-teams.ts), så de matcher direkte mod
 * wc_matches.home_team/away_team.
 *
 * Datoer og kickoff-tider offentliggøres først 29. august 2026; kampene
 * oprettes derfor uden match_date, og syncen fylder datoerne på når de findes.
 * Rækkefølgen her er katalogorden (styrke), ikke spillerækkefølge.
 */
export const CL2627_LEAGUE_FIXTURES: readonly (readonly [home: string, away: string])[] = [
  ["Bayern München",      "Arsenal"],
  ["Bayern München",      "Bodø/Glimt"],
  ["Bayern München",      "Real Betis"],
  ["Bayern München",      "Slavia Praha"],
  ["Arsenal",             "Real Madrid"],
  ["Arsenal",             "Borussia Dortmund"],
  ["Arsenal",             "Lille"],
  ["Arsenal",             "Sabah FK"],
  ["PSG",                 "Barcelona"],
  ["PSG",                 "AS Roma"],
  ["PSG",                 "Galatasaray"],
  ["PSG",                 "Slovan Bratislava"],
  ["Barcelona",           "Manchester City"],
  ["Barcelona",           "Aston Villa"],
  ["Barcelona",           "Como"],
  ["Barcelona",           "Feyenoord"],
  ["Real Madrid",         "Inter"],
  ["Real Madrid",         "PSV"],
  ["Real Madrid",         "RB Leipzig"],
  ["Real Madrid",         "LASK Linz"],
  ["Manchester City",     "PSG"],
  ["Manchester City",     "Sporting CP"],
  ["Manchester City",     "Napoli"],
  ["Manchester City",     "AEK Athen"],
  ["Inter",               "Liverpool"],
  ["Inter",               "VfB Stuttgart"],
  ["Inter",               "Club Brugge"],
  ["Inter",               "Shakhtar Donetsk"],
  ["Manchester United",   "Bayern München"],
  ["Manchester United",   "AS Roma"],
  ["Manchester United",   "RB Leipzig"],
  ["Manchester United",   "Sabah FK"],
  ["Aston Villa",         "PSG"],
  ["Aston Villa",         "Borussia Dortmund"],
  ["Aston Villa",         "Fenerbahçe"],
  ["Aston Villa",         "Viking FK"],
  ["Borussia Dortmund",   "Inter"],
  ["Borussia Dortmund",   "Real Betis"],
  ["Borussia Dortmund",   "Villarreal"],
  ["Borussia Dortmund",   "AEK Athen"],
  ["Sporting CP",         "Barcelona"],
  ["Sporting CP",         "Manchester United"],
  ["Sporting CP",         "Galatasaray"],
  ["Sporting CP",         "LASK Linz"],
  ["AS Roma",             "Real Madrid"],
  ["AS Roma",             "Sporting CP"],
  ["AS Roma",             "Lille"],
  ["AS Roma",             "Slovan Bratislava"],
  ["Como",                "PSG"],
  ["Como",                "Manchester United"],
  ["Como",                "RB Leipzig"],
  ["Como",                "AEK Athen"],
  ["Liverpool",           "Atlético Madrid"],
  ["Liverpool",           "FC Porto"],
  ["Liverpool",           "RC Lens"],
  ["Liverpool",           "Villarreal"],
  ["PSV",                 "Atlético Madrid"],
  ["PSV",                 "VfB Stuttgart"],
  ["PSV",                 "Club Brugge"],
  ["PSV",                 "Shakhtar Donetsk"],
  ["Atlético Madrid",     "Bayern München"],
  ["Atlético Madrid",     "Manchester United"],
  ["Atlético Madrid",     "Fenerbahçe"],
  ["Atlético Madrid",     "Viking FK"],
  ["FC Porto",            "Manchester City"],
  ["FC Porto",            "PSV"],
  ["FC Porto",            "Napoli"],
  ["FC Porto",            "Slavia Praha"],
  ["Napoli",              "Arsenal"],
  ["Napoli",              "Club Brugge"],
  ["Napoli",              "Bodø/Glimt"],
  ["Napoli",              "Viking FK"],
  ["VfB Stuttgart",       "Atlético Madrid"],
  ["VfB Stuttgart",       "Club Brugge"],
  ["VfB Stuttgart",       "Lille"],
  ["VfB Stuttgart",       "Viking FK"],
  ["Club Brugge",         "Aston Villa"],
  ["Club Brugge",         "Liverpool"],
  ["Club Brugge",         "Bodø/Glimt"],
  ["Club Brugge",         "RC Lens"],
  ["RB Leipzig",          "Manchester City"],
  ["RB Leipzig",          "PSV"],
  ["RB Leipzig",          "RC Lens"],
  ["RB Leipzig",          "Shakhtar Donetsk"],
  ["Bodø/Glimt",          "Borussia Dortmund"],
  ["Bodø/Glimt",          "Atlético Madrid"],
  ["Bodø/Glimt",          "Lille"],
  ["Bodø/Glimt",          "LASK Linz"],
  ["RC Lens",             "Manchester City"],
  ["RC Lens",             "Sporting CP"],
  ["RC Lens",             "Como"],
  ["RC Lens",             "Bodø/Glimt"],
  ["Real Betis",          "Arsenal"],
  ["Real Betis",          "Como"],
  ["Real Betis",          "FC Porto"],
  ["Real Betis",          "Feyenoord"],
  ["Villarreal",          "PSG"],
  ["Villarreal",          "Manchester United"],
  ["Villarreal",          "Napoli"],
  ["Villarreal",          "Sabah FK"],
  ["Galatasaray",         "Barcelona"],
  ["Galatasaray",         "Aston Villa"],
  ["Galatasaray",         "VfB Stuttgart"],
  ["Galatasaray",         "Feyenoord"],
  ["Lille",               "Bayern München"],
  ["Lille",               "Real Betis"],
  ["Lille",               "Galatasaray"],
  ["Lille",               "Slovan Bratislava"],
  ["Slavia Praha",        "Arsenal"],
  ["Slavia Praha",        "Aston Villa"],
  ["Slavia Praha",        "RC Lens"],
  ["Slavia Praha",        "Villarreal"],
  ["Fenerbahçe",          "AS Roma"],
  ["Fenerbahçe",          "Liverpool"],
  ["Fenerbahçe",          "Villarreal"],
  ["Fenerbahçe",          "Slavia Praha"],
  ["Shakhtar Donetsk",    "Real Madrid"],
  ["Shakhtar Donetsk",    "Sporting CP"],
  ["Shakhtar Donetsk",    "Fenerbahçe"],
  ["Shakhtar Donetsk",    "AEK Athen"],
  ["AEK Athen",           "Real Madrid"],
  ["AEK Athen",           "AS Roma"],
  ["AEK Athen",           "Galatasaray"],
  ["AEK Athen",           "LASK Linz"],
  ["Feyenoord",           "Inter"],
  ["Feyenoord",           "Como"],
  ["Feyenoord",           "FC Porto"],
  ["Feyenoord",           "RB Leipzig"],
  ["Viking FK",           "Bayern München"],
  ["Viking FK",           "PSV"],
  ["Viking FK",           "Feyenoord"],
  ["Viking FK",           "Sabah FK"],
  ["Slovan Bratislava",   "Inter"],
  ["Slovan Bratislava",   "VfB Stuttgart"],
  ["Slovan Bratislava",   "Real Betis"],
  ["Slovan Bratislava",   "Shakhtar Donetsk"],
  ["LASK Linz",           "Liverpool"],
  ["LASK Linz",           "FC Porto"],
  ["LASK Linz",           "Fenerbahçe"],
  ["LASK Linz",           "Slovan Bratislava"],
  ["Sabah FK",            "Barcelona"],
  ["Sabah FK",            "Borussia Dortmund"],
  ["Sabah FK",            "Napoli"],
  ["Sabah FK",            "Slavia Praha"],
];
